//AUTH
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCESS";
export const AUTH_FAIL = "AUTH_FAIL";

//LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

//GET RECIPE
export const GET_RECIPE_REQUEST = "GET_RECIPE_REQUEST";
export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCESS";
export const GET_RECIPE_FAIL = "GET_RECIPE_FAIL";

//GET INGREDIENT
export const GET_INGREDIENT_REQUEST = "GET_INGREDIENT_REQUEST";
export const GET_INGREDIENT_SUCCESS = "GET_INGREDIENT_SUCESS";
export const GET_INGREDIENT_FAIL = "GET_INGREDIENT_FAIL";

//GET PROCESS
export const GET_PROCESS_REQUEST = "GET_PROCESS_REQUEST";
export const GET_PROCESS_SUCCESS = "GET_PROCESS_SUCESS";
export const GET_PROCESS_FAIL = "GET_PROCESS_FAIL";


//CLEAR ERROR
export const CLEAR_ERROR = "CLEAR_ERROR"